#### This is the Pandas and Matplotlib homework for GEOG 592. 
Name: Anna Horton
ONYEN: arhorton

This will be a mix of code and markdown cells so that I can answer the questions in the format that they are best answered.

Question One:
The df is the object and the method is the .head(); the .head() method uses dot notation.

Question Two:
df.shape is an attribute. It stores information about the object. If the code does not include a parentheses, the code is referring to an attribute; only methods use parentheses to denote their correct symbology.

Question Three: 
The dataset has 75 columns and 8 rows.

Question Four: 
When a single dataframe column is called, usually by syntax like dataframe["Yes/No Response"], a pandas Series object is produced.

Question Five:
When multiple columns are called from the dataframe, the output is usually a pandas DataFrame of its own. The two columns together create a dataframe with values associated.

In [35]:
## Code for a few further questions!
import pandas as pd
parks = pd.DataFrame({"Park": ["Oak", "Pine", "Maple", "Cedar"], "Area": [12, 25, 18, 40], "Visitors": [120, 250, 180, 310]})
print(parks)

    Park  Area  Visitors
0    Oak    12       120
1   Pine    25       250
2  Maple    18       180
3  Cedar    40       310

Question 6 and 7 are below.

In [36]:
## Question 6 answer
parks["Visitors"]
print(parks["Visitors"])

## Question 7 answer
parks[["Park", "Visitors"]]
print(parks[["Park", "Visitors"]])

0    120
1    250
2    180
3    310
Name: Visitors, dtype: int64
    Park  Visitors
0    Oak       120
1   Pine       250
2  Maple       180
3  Cedar       310

Question 8: 
parks.iloc[0] will return the zeroth row of the dataset, which in this case belongs to the Oak Park, its area and its visitors. The .iloc() method allows for the references to be called to by index position.

In [37]:
## Question 8 answer
parks.iloc[0]

Park        Oak
Area         12
Visitors    120
Name: 0, dtype: object

Question 9:
The rows that are selected for in parks.iloc[1:4] are the first three rows. Though the fourth row appears to be included, it only selected the rows from 1 to 3 and the fourth is not included.

In [38]:
## Question 9 answer
parks.iloc[1:4]

    Park  Area  Visitors
1   Pine    25       250
2  Maple    18       180
3  Cedar    40       310

Question Ten:
The answer to question 10 is below. This code works because there are only three rows, so the four is not involved at all; the 2 starts the slicing and the slicing ends at the third row.

In [39]:
## Question 10 answer
parks.iloc[2:4][["Park", "Area"]]

    Park  Area
2  Maple    18
3  Cedar    40

Question 11:
The answer to question 11 is below.

In [40]:
## Question 11 answer
mask = parks["Area"] > 20

Question 12:
The rows that are kept after using the mask/Boolean filter are only those that have an area larger than 20. In this case, that is only two parks: Pine and Cedar.

Question 13:
The answer to question 13 is below.

In [41]:
## Question 13 answer
large_parks = parks[mask].copy()

Question 14:
The .copy() method is useful after filtering because it makes an individual copy of the filtered dataframe with its own memory. With the dataframe saved like that, any edits that are made to the new one do not affect what is stored in memory for the older one. It allows you to retrace your steps if needed.

Question 15:
The answer to question 15 is below.

In [42]:
## Question 15 answer
parks.columns = [["Name", "Area_ha", "Annual Visitors"]]

Question 16:
If the new column names only have two elements and the original dataframe has three columns, when the code tries to rename the columns, it will throw an error. There are a different number of objects within the lists that the code is trying to compare to each other, which leaves it confused and throwing an error.

In [43]:
## Code for the next few questions!
values = pd.Series(["12.5", "18.0", "missing", "22.5"])

Question 17:
This pandas.Series will likely store the numbers as strings because they each have the quotation marks around them. The Python string denotation syntax requires a ' or " around both sides of the element, and these numbers are represented in that format.

Question 18:
The answer to question 18 is below.

In [44]:
## Question 18 answer
values = pd.to_numeric(values, errors = "coerce")
print(values)

0    12.5
1    18.0
2     NaN
3    22.5
dtype: float64

Question 19:
The "missing" value from the original values Series gets an NaN. This is code for "Not a number", which is what Python substites for anything

Question 20:
The is.na().sum() combination of methods spits out a sum of the total number of NA values within the rows. The .isna() method by itself returns a Boolean, where True denotes where there is an NA value and false in the opposite case.

Question 21:
The .dropna() method removes the rows that contain NA values from the dataframe entirely; the .fillna() method fills in where there are NA values with some other value that you select. There should be much thought that goes into eliminating or replacing NA values, as this alters the original dataframe and can change the results of the data analysis that is being conducted.

Question 22: 
The answer to question 22 is below.

In [51]:
## Question 22 answer
parks.sort_values("Visitors", ascending = False)

KeyError: 'Visitors'